### ISSUE TITLE
Cần mô tả rõ hơn về 2 hành động mua và bán

### ISSUE THREAD

**Issue by longlile** [Duanthse03268/Loduna#2]
Cần mô tả rõ hơn về 2 hành động mua và bán như sau : 
1. Khi user mua BTC từ VNĐ.
2. Khi user bán BTC về VNĐ.
lưu trữ BTC và VNĐ sẽ ở trên hệ thống của mình. Vậy thì khi chuyển về VNĐ sẽ thực hiện luôn giao dịch chuyển tiền từ tài khoản hệ thống về tài khoản nhận tiền của user chứ ?

**Comment by Duanthse03268** [comment]
Tất cả chỉ là giao dịch theo kiểu dữ liệu trên hệ thống thôi. Khi nào user rút tiền mới chuyển ra
